spring.application.name=demo
# Conexión a Neon PostgreSQL
spring.datasource.url=jdbc:postgresql://ep-wandering-hat-ami5kkzu-pooler.c-5.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.jpa.properties.hibernate.default_schema=servicio
spring.datasource.username=neondb_owner
spring.datasource.password=npg_BEoLKi8dSA9m
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true